"""Additional methods for GeminiRAHelper.

This file contains new helper methods for subscription pause and time shift operations
to be merged into helper/gemini_ra_helper.py.

Target File: helper/gemini_ra_helper.py
Test Case: C44873414 - Billing Cycle Period card
Generated by: Test Script Generator

MERGE INSTRUCTIONS:
1. Add these static methods to the existing GeminiRAHelper class
2. Maintain consistent indentation and coding style with the existing file
3. Import framework_logger if not already imported

MERGE NOTES:
- These methods encapsulate Rails Admin workflows for better test readability
- pause_subscription() implements the missing pause action from V007
- shift_time_and_trigger_billing() encapsulates the admin workflow from V009
"""

from core.settings import framework_logger


class GeminiRAHelper:
    """Additional helper methods for GeminiRAHelper class.
    
    These should be merged into the existing GeminiRAHelper class.
    All methods are static and follow the existing helper pattern.
    """

    @staticmethod
    def pause_subscription(page):
        """Pauses the subscription via Rails Admin edit menu.
        
        Args:
            page: Playwright page object
        
        This method accesses the edit menu, selects the pause event or sets
        the subscription state to paused, and saves the changes.
        """
        # Access edit menu
        page.locator('a:has-text("Edit")').click()
        page.wait_for_load_state('networkidle', timeout=30000)
        
        # Select pause event or set state to paused
        # Implementation depends on Rails Admin UI structure
        page.locator('select[name="subscription[state]"]').select_option('paused')
        
        # Save changes
        page.locator('button:has-text("Save")').click()
        page.wait_for_load_state('networkidle', timeout=30000)
        framework_logger.info('Subscription paused via Rails Admin')

    @staticmethod
    def shift_time_and_trigger_billing(page, tenant_email: str, days: int):
        """Shifts time by specified days and triggers billing for a tenant.
        
        Args:
            page: Playwright page object
            tenant_email: Email of the tenant
            days: Number of days to shift
        
        This method encapsulates the complete admin workflow sequence:
        1. Access Rails Admin
        2. Navigate to tenant page
        3. Perform event shift with billing trigger
        """
        GeminiRAHelper.access(page)
        GeminiRAHelper.access_tenant_page(page, tenant_email)
        GeminiRAHelper.event_shift(page, event_shift=days, force_billing=True)
        framework_logger.info(f'Time shifted {days} days and billing triggered for {tenant_email}')
