"""Additional methods for GeminiRAHelper.

This file contains new helper methods for Rails Admin operations
to be merged into helper/gemini_ra_helper.py.

Target File: helper/gemini_ra_helper.py
Test Case: C44873414 - Billing Cycle Period card
Generated by: Test Script Generator

MERGE INSTRUCTIONS:
1. Open helper/gemini_ra_helper.py in your editor
2. Locate the GeminiRAHelper class definition
3. Add the method(s) below to the class (maintain alphabetical order if possible)
4. Ensure all methods are decorated with @staticmethod
5. Maintain consistent 4-space indentation throughout
6. Save the file and run the test to verify the method works correctly

MERGE NOTES:
- This method encapsulates the pause subscription operation via Rails Admin
- It replaces inline page.locator() calls in test scripts
- The method handles navigation, selection, and saving in one call
"""


@staticmethod
def pause_subscription_via_rails_admin(page):
    """Pause subscription via Rails Admin interface.
    
    Navigates to the subscription edit page, selects the paused state,
    and saves the changes. This method encapsulates the entire pause
    operation to avoid inline page.locator() calls in test scripts.
    
    Args:
        page: Playwright Page object
    
    Returns:
        None
    
    Raises:
        TimeoutError: If any element is not found within timeout
        AssertionError: If save operation fails
    """
    page.locator("a:has-text('Edit')").first.click()
    page.wait_for_load_state('networkidle', timeout=30000)
    page.locator("select[name='subscription[subscription_state]']").select_option('paused')
    page.locator("input[type='submit'][value='Save']").click()
    page.wait_for_load_state('networkidle', timeout=30000)
