"""Additional locators and methods for PrintHistoryPage.

This file contains new locators and verification methods for the Billing Cycle Period card
functionality to be merged into pages/print_history_page.py.

Target File: pages/print_history_page.py
Test Case: C44873414 - Billing Cycle Period card
Generated by: Test Script Generator

MERGE INSTRUCTIONS:
1. Add 'from playwright.sync_api import expect' at module level in print_history_page.py if not present
2. Locate the existing __init__ method in PrintHistoryPage
3. Add the locator property definitions shown below after existing locators in __init__
4. Add the verification methods shown below to the class body
5. Remove 'from playwright.sync_api import expect' from inside each method if present
6. Maintain consistent indentation with the existing file

WARNINGS:
- Tooltip selectors use generic [role='tooltip'] which may match multiple elements
- Consider using data-testid attributes for tooltips if available
- Test all new locators after merge to ensure correct element targeting
"""


# ═══════════════════════════════════════════════════════════════════════════════
# ADD THE FOLLOWING CODE TO THE __init__ METHOD OF PrintHistoryPage
# (Insert after self.elements = self.Elements() or after existing locator definitions)
# ═══════════════════════════════════════════════════════════════════════════════

# Billing Cycle Period Card locators as properties
self.plan_pause_info = page.locator("[data-testid='plan-pause-info']")
self.billing_cycle_period_card = page.locator("[data-testid='billing-cycle-period-card']")

# Complimentary Pages locators as properties
self.complimentary_pages_progress_bar = page.locator("[data-testid='complimentary-pages-progress-bar']")
self.complimentary_pages_value = page.locator("[data-testid='complimentary-pages-value']")
self.complimentary_pages_info_icon = page.locator("[data-testid='complimentary-pages-info-icon']")
self.complimentary_pages_info_message = page.locator("[data-testid='complimentary-pages-info-message']")
self.complimentary_pages_tooltip = page.locator("[role='tooltip']")

# Additional Pages locators as properties
self.additional_pages_progress_bar = page.locator("[data-testid='additional-pages-progress-bar']")
self.additional_pages_value = page.locator("[data-testid='additional-pages-value']")
self.additional_pages_info_icon = page.locator("[data-testid='additional-pages-info-icon']")
self.additional_pages_info_message = page.locator("[data-testid='additional-pages-info-message']")
self.additional_pages_tooltip = page.locator("[role='tooltip']")


# ═══════════════════════════════════════════════════════════════════════════════
# ADD THE FOLLOWING METHODS TO THE PrintHistoryPage CLASS BODY
# ═══════════════════════════════════════════════════════════════════════════════

def verify_plan_pause_info_not_displayed(self):
    """Verify plan pause information is not displayed."""
    expect(self.plan_pause_info).not_to_be_visible(timeout=10000)


def verify_plan_pause_info_displayed(self):
    """Verify plan pause information is displayed."""
    expect(self.plan_pause_info).to_be_visible(timeout=30000)


def verify_complimentary_pages_value(self, expected_used, expected_total, pause_plan=True):
    """Verify complimentary pages value displays correct usage."""
    expect(self.complimentary_pages_value).to_contain_text(f"{expected_used} of {expected_total}", timeout=30000)
    if pause_plan:
        expect(self.complimentary_pages_value).to_contain_text("Pause Plan", timeout=30000)


def hover_complimentary_info_icon(self):
    """Hover over complimentary pages info icon to display tooltip."""
    expect(self.complimentary_pages_info_icon).to_be_visible(timeout=30000)
    self.complimentary_pages_info_icon.hover()


def verify_additional_pages_value(self, expected_used, expected_total):
    """Verify additional pages value displays correct usage."""
    expect(self.additional_pages_value).to_contain_text(f"{expected_used} of {expected_total}", timeout=30000)
