"""Additional locators and methods for PrintHistoryPage.

This file contains new locators and verification methods for the Billing Cycle Period card
functionality to be merged into pages/print_history_page.py.

Target File: pages/print_history_page.py
Test Case: C44873414 - Billing Cycle Period card
Generated by: Test Script Generator

MERGE INSTRUCTIONS:
1. Add the locator definitions shown below to the existing Elements inner class in PrintHistoryPage
2. Add the property methods shown below to the PrintHistoryPage class __init__ method
3. Add the verification methods shown below to the PrintHistoryPage class body
4. Maintain consistent indentation with the existing file

MERGE NOTES:
- Tooltip selectors may need to be updated with specific data-testid attributes when available
- Verify all locators target correct elements after merge
- Test tooltip interactions on both desktop (hover) and mobile (click)
"""


# ═══════════════════════════════════════════════════════════════════════════════
# REQUIRED IMPORT (add to module level in print_history_page.py if not present)
# ═══════════════════════════════════════════════════════════════════════════════

from playwright.sync_api import expect


# ═══════════════════════════════════════════════════════════════════════════════
# ADD TO EXISTING PrintHistoryPage.Elements CLASS
# (These are additions to the existing Elements inner class, not a new class)
# ═══════════════════════════════════════════════════════════════════════════════

class Elements:
    plan_pause_info = "[data-testid='plan-pause-info']"
    billing_cycle_period_card = "[data-testid='billing-cycle-period-card']"
    complimentary_pages_progress_bar = "[data-testid='complimentary-pages-progress-bar']"
    complimentary_pages_value = "[data-testid='complimentary-pages-value']"
    complimentary_pages_info_icon = "[data-testid='complimentary-pages-info-icon']"
    complimentary_pages_info_message = "[data-testid='complimentary-pages-info-message']"
    complimentary_pages_tooltip = "[data-testid='complimentary-pages-tooltip']"
    additional_pages_progress_bar = "[data-testid='additional-pages-progress-bar']"
    additional_pages_value = "[data-testid='additional-pages-value']"
    additional_pages_info_icon = "[data-testid='additional-pages-info-icon']"
    additional_pages_info_message = "[data-testid='additional-pages-info-message']"
    additional_pages_tooltip = "[data-testid='additional-pages-tooltip']"


# ═══════════════════════════════════════════════════════════════════════════════
# ADD TO PrintHistoryPage.__init__ METHOD
# (Add these property initializations after super().__init__(page))
# ═══════════════════════════════════════════════════════════════════════════════

# def __init__(self, page: Page):
#     super().__init__(page)
#     self.plan_pause_info = page.locator(self.elements.plan_pause_info)
#     self.billing_cycle_period_card = page.locator(self.elements.billing_cycle_period_card)
#     self.complimentary_pages_progress_bar = page.locator(self.elements.complimentary_pages_progress_bar)
#     self.complimentary_pages_value = page.locator(self.elements.complimentary_pages_value)
#     self.complimentary_pages_info_icon = page.locator(self.elements.complimentary_pages_info_icon)
#     self.complimentary_pages_info_message = page.locator(self.elements.complimentary_pages_info_message)
#     self.complimentary_pages_tooltip = page.locator(self.elements.complimentary_pages_tooltip)
#     self.additional_pages_progress_bar = page.locator(self.elements.additional_pages_progress_bar)
#     self.additional_pages_value = page.locator(self.elements.additional_pages_value)
#     self.additional_pages_info_icon = page.locator(self.elements.additional_pages_info_icon)
#     self.additional_pages_info_message = page.locator(self.elements.additional_pages_info_message)
#     self.additional_pages_tooltip = page.locator(self.elements.additional_pages_tooltip)


# ═══════════════════════════════════════════════════════════════════════════════
# ADD THE FOLLOWING METHODS TO THE PrintHistoryPage CLASS BODY
# ═══════════════════════════════════════════════════════════════════════════════

def verify_plan_pause_info_not_displayed(self):
    """Verify plan pause information is not displayed."""
    expect(self.plan_pause_info).not_to_be_visible(timeout=10000)


def verify_plan_pause_info_displayed(self):
    """Verify plan pause information is displayed."""
    expect(self.plan_pause_info).to_be_visible(timeout=30000)


def verify_complimentary_pages_value(self, expected_used, expected_total, pause_plan=True):
    """Verify complimentary pages value displays correct usage."""
    expect(self.complimentary_pages_value).to_contain_text(f"{expected_used} of {expected_total}", timeout=30000)
    if pause_plan:
        expect(self.complimentary_pages_value).to_contain_text("Pause Plan", timeout=30000)


def hover_complimentary_info_icon(self):
    """Hover over complimentary pages info icon to display tooltip."""
    expect(self.complimentary_pages_info_icon).to_be_visible(timeout=30000)
    self.complimentary_pages_info_icon.hover()


def verify_additional_pages_value(self, expected_used, expected_total):
    """Verify additional pages value displays correct usage."""
    expect(self.additional_pages_value).to_contain_text(f"{expected_used} of {expected_total}", timeout=30000)
